updating version of python
uc-cdis/dictionaryutils pull request #76
Opened 2022-05-03 18:42 UTC by MichaelLukowski

### Dependency updates
Python version upgrade in poetry

2022-05-03 19:08 UTC, SpencerAxelrod approved these changes

2022-05-03 19:27 UTC, paulineribeyre requested changes

2022-05-03 19:27 UTC, paulineribeyre commented on pyproject.toml
> +python = ">=3.6,<=3.9"
could you update the travis file to test 3.9

2022-05-09 20:39 UTC, paulineribeyre approved these changes

2022-05-09 20:41 UTC, merged